sudo: required
dist: xenial

services:
- docker

env:
- BUILDER_NAME="k8s-nativelb/${TRAVIS_JOB_ID}builder" CPLATFORM=minikube CDIST=kubernetes CVER=1.11.3

#jobs:
#  include:
#  - stage: Tests
#    name: "minikube (1.11)"
#    env: CPLATFORM=minikube CDIST=kubernetes CVER=1.11.3
#
#  - name: "oc cluster (3.10)"
#    env: CPLATFORM=oc_cluster CDIST=origin CVER=3.10.0
#
#  - name: "minishift (3.10)"
#    env: CPLATFORM=minishift CDIST=origin CVER=3.10.0

# TODO: Include a job for unittest only

cache:
  directories:
  - cache
  - "~/.minishift/cache"
  - "~/.minikube/cache"

before_script:
## FIXME Workaround for https://github.com/kubernetes/kubernetes/issues/61058
### And https://github.com/LiliC/travis-minikube/blob/e0f26f7b388057f51a0e2558afd5f990e07b6c49/.travis.yml#L11
- sudo mount --make-rshared /
- bash -x ci/prepare-host $CPLATFORM $CVER
- bash -x ci/start-cluster $CPLATFORM $CVER
- bash -x ci/deploy-nativelb $CPLATFORM $CVER

script:
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run make. Please run it and commit the changes"; git status --porcelain; false; fi
- timeout 10m bash -x make docker-test
- timeout 20m bash -x make docker-functest

deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make docker-push
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make docker-push IMAGE_TAG=$TRAVIS_TAG
  skip_cleanup: true
  file:
  on:
    tags: true

notifications:
  slack: nativelb:qSryTAFxzsFUgMusY0I06N5R
