// Code generated by protoc-gen-go. DO NOT EDIT.
// source: native-lb.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Command              string    `protobuf:"bytes,1,opt,name=Command" json:"Command,omitempty"`
	Servers              []*Server `protobuf:"bytes,2,rep,name=Servers" json:"Servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{0}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Command) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

type Agent struct {
	HostName             string   `protobuf:"bytes,1,opt,name=HostName" json:"HostName,omitempty"`
	IPAddress            string   `protobuf:"bytes,2,opt,name=IPAddress" json:"IPAddress,omitempty"`
	Cluster              string   `protobuf:"bytes,3,opt,name=Cluster" json:"Cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{1}
}
func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (dst *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(dst, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Agent) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

func (m *Agent) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type AgentStatus struct {
	Name                 string               `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Pid                  int32                `protobuf:"varint,2,opt,name=Pid" json:"Pid,omitempty"`
	StartTime            string               `protobuf:"bytes,3,opt,name=StartTime" json:"StartTime,omitempty"`
	Time                 string               `protobuf:"bytes,4,opt,name=Time" json:"Time,omitempty"`
	Uptime               *timestamp.Timestamp `protobuf:"bytes,5,opt,name=Uptime" json:"Uptime,omitempty"`
	Version              string               `protobuf:"bytes,6,opt,name=Version" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AgentStatus) Reset()         { *m = AgentStatus{} }
func (m *AgentStatus) String() string { return proto.CompactTextString(m) }
func (*AgentStatus) ProtoMessage()    {}
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{2}
}
func (m *AgentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentStatus.Unmarshal(m, b)
}
func (m *AgentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentStatus.Marshal(b, m, deterministic)
}
func (dst *AgentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentStatus.Merge(dst, src)
}
func (m *AgentStatus) XXX_Size() int {
	return xxx_messageInfo_AgentStatus.Size(m)
}
func (m *AgentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AgentStatus proto.InternalMessageInfo

func (m *AgentStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentStatus) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *AgentStatus) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *AgentStatus) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *AgentStatus) GetUptime() *timestamp.Timestamp {
	if m != nil {
		return m.Uptime
	}
	return nil
}

func (m *AgentStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ServerStats struct {
	Name                 string     `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	ActiveConnections    int32      `protobuf:"varint,2,opt,name=ActiveConnections" json:"ActiveConnections,omitempty"`
	RxTotal              int32      `protobuf:"varint,3,opt,name=RxTotal" json:"RxTotal,omitempty"`
	TxTotal              int32      `protobuf:"varint,4,opt,name=TxTotal" json:"TxTotal,omitempty"`
	RxSecond             int32      `protobuf:"varint,5,opt,name=RxSecond" json:"RxSecond,omitempty"`
	TxSecond             int32      `protobuf:"varint,6,opt,name=TxSecond" json:"TxSecond,omitempty"`
	Backends             []*Backend `protobuf:"bytes,7,rep,name=Backends" json:"Backends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerStats) Reset()         { *m = ServerStats{} }
func (m *ServerStats) String() string { return proto.CompactTextString(m) }
func (*ServerStats) ProtoMessage()    {}
func (*ServerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{3}
}
func (m *ServerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStats.Unmarshal(m, b)
}
func (m *ServerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStats.Marshal(b, m, deterministic)
}
func (dst *ServerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStats.Merge(dst, src)
}
func (m *ServerStats) XXX_Size() int {
	return xxx_messageInfo_ServerStats.Size(m)
}
func (m *ServerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStats proto.InternalMessageInfo

func (m *ServerStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerStats) GetActiveConnections() int32 {
	if m != nil {
		return m.ActiveConnections
	}
	return 0
}

func (m *ServerStats) GetRxTotal() int32 {
	if m != nil {
		return m.RxTotal
	}
	return 0
}

func (m *ServerStats) GetTxTotal() int32 {
	if m != nil {
		return m.TxTotal
	}
	return 0
}

func (m *ServerStats) GetRxSecond() int32 {
	if m != nil {
		return m.RxSecond
	}
	return 0
}

func (m *ServerStats) GetTxSecond() int32 {
	if m != nil {
		return m.TxSecond
	}
	return 0
}

func (m *ServerStats) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type Server struct {
	Bind                     string       `protobuf:"bytes,1,opt,name=Bind" json:"Bind,omitempty"`
	Protocol                 string       `protobuf:"bytes,2,opt,name=Protocol" json:"Protocol,omitempty"`
	UDP                      *UDP         `protobuf:"bytes,3,opt,name=UDP" json:"UDP,omitempty"`
	Balance                  string       `protobuf:"bytes,4,opt,name=Balance" json:"Balance,omitempty"`
	MaxConnections           string       `protobuf:"bytes,5,opt,name=MaxConnections" json:"MaxConnections,omitempty"`
	ClientIdleTimeout        string       `protobuf:"bytes,6,opt,name=ClientIdleTimeout" json:"ClientIdleTimeout,omitempty"`
	BackendIdleTimeout       string       `protobuf:"bytes,7,opt,name=BackendIdleTimeout" json:"BackendIdleTimeout,omitempty"`
	BackendConnectionTimeout string       `protobuf:"bytes,8,opt,name=BackendConnectionTimeout" json:"BackendConnectionTimeout,omitempty"`
	Discovery                *Discovery   `protobuf:"bytes,9,opt,name=Discovery" json:"Discovery,omitempty"`
	HealthCheck              *HealthCheck `protobuf:"bytes,10,opt,name=HealthCheck" json:"HealthCheck,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}     `json:"-"`
	XXX_unrecognized         []byte       `json:"-"`
	XXX_sizecache            int32        `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{4}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (dst *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(dst, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *Server) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Server) GetUDP() *UDP {
	if m != nil {
		return m.UDP
	}
	return nil
}

func (m *Server) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Server) GetMaxConnections() string {
	if m != nil {
		return m.MaxConnections
	}
	return ""
}

func (m *Server) GetClientIdleTimeout() string {
	if m != nil {
		return m.ClientIdleTimeout
	}
	return ""
}

func (m *Server) GetBackendIdleTimeout() string {
	if m != nil {
		return m.BackendIdleTimeout
	}
	return ""
}

func (m *Server) GetBackendConnectionTimeout() string {
	if m != nil {
		return m.BackendConnectionTimeout
	}
	return ""
}

func (m *Server) GetDiscovery() *Discovery {
	if m != nil {
		return m.Discovery
	}
	return nil
}

func (m *Server) GetHealthCheck() *HealthCheck {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

type Discovery struct {
	Kind                 string         `protobuf:"bytes,1,opt,name=Kind" json:"Kind,omitempty"`
	BackendSpec          []*BackendSpec `protobuf:"bytes,2,rep,name=BackendSpec" json:"BackendSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Discovery) Reset()         { *m = Discovery{} }
func (m *Discovery) String() string { return proto.CompactTextString(m) }
func (*Discovery) ProtoMessage()    {}
func (*Discovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{5}
}
func (m *Discovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discovery.Unmarshal(m, b)
}
func (m *Discovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discovery.Marshal(b, m, deterministic)
}
func (dst *Discovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discovery.Merge(dst, src)
}
func (m *Discovery) XXX_Size() int {
	return xxx_messageInfo_Discovery.Size(m)
}
func (m *Discovery) XXX_DiscardUnknown() {
	xxx_messageInfo_Discovery.DiscardUnknown(m)
}

var xxx_messageInfo_Discovery proto.InternalMessageInfo

func (m *Discovery) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Discovery) GetBackendSpec() []*BackendSpec {
	if m != nil {
		return m.BackendSpec
	}
	return nil
}

type HealthCheck struct {
	Fails                int32    `protobuf:"varint,1,opt,name=Fails" json:"Fails,omitempty"`
	Passes               int32    `protobuf:"varint,2,opt,name=Passes" json:"Passes,omitempty"`
	Interval             string   `protobuf:"bytes,3,opt,name=Interval" json:"Interval,omitempty"`
	Timeout              string   `protobuf:"bytes,4,opt,name=Timeout" json:"Timeout,omitempty"`
	Kind                 string   `protobuf:"bytes,5,opt,name=Kind" json:"Kind,omitempty"`
	PingTimeoutDuration  string   `protobuf:"bytes,6,opt,name=PingTimeoutDuration" json:"PingTimeoutDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{6}
}
func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (dst *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(dst, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetFails() int32 {
	if m != nil {
		return m.Fails
	}
	return 0
}

func (m *HealthCheck) GetPasses() int32 {
	if m != nil {
		return m.Passes
	}
	return 0
}

func (m *HealthCheck) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *HealthCheck) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *HealthCheck) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *HealthCheck) GetPingTimeoutDuration() string {
	if m != nil {
		return m.PingTimeoutDuration
	}
	return ""
}

type UDP struct {
	MaxRequests          int32    `protobuf:"varint,1,opt,name=MaxRequests" json:"MaxRequests,omitempty"`
	MaxResponses         int32    `protobuf:"varint,2,opt,name=MaxResponses" json:"MaxResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UDP) Reset()         { *m = UDP{} }
func (m *UDP) String() string { return proto.CompactTextString(m) }
func (*UDP) ProtoMessage()    {}
func (*UDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{7}
}
func (m *UDP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UDP.Unmarshal(m, b)
}
func (m *UDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UDP.Marshal(b, m, deterministic)
}
func (dst *UDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UDP.Merge(dst, src)
}
func (m *UDP) XXX_Size() int {
	return xxx_messageInfo_UDP.Size(m)
}
func (m *UDP) XXX_DiscardUnknown() {
	xxx_messageInfo_UDP.DiscardUnknown(m)
}

var xxx_messageInfo_UDP proto.InternalMessageInfo

func (m *UDP) GetMaxRequests() int32 {
	if m != nil {
		return m.MaxRequests
	}
	return 0
}

func (m *UDP) GetMaxResponses() int32 {
	if m != nil {
		return m.MaxResponses
	}
	return 0
}

type Backend struct {
	BackendSpec          *BackendSpec   `protobuf:"bytes,1,opt,name=BackendSpec" json:"BackendSpec,omitempty"`
	BackendStatus        *BackendStatus `protobuf:"bytes,2,opt,name=BackendStatus" json:"BackendStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Backend) Reset()         { *m = Backend{} }
func (m *Backend) String() string { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()    {}
func (*Backend) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{8}
}
func (m *Backend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backend.Unmarshal(m, b)
}
func (m *Backend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backend.Marshal(b, m, deterministic)
}
func (dst *Backend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backend.Merge(dst, src)
}
func (m *Backend) XXX_Size() int {
	return xxx_messageInfo_Backend.Size(m)
}
func (m *Backend) XXX_DiscardUnknown() {
	xxx_messageInfo_Backend.DiscardUnknown(m)
}

var xxx_messageInfo_Backend proto.InternalMessageInfo

func (m *Backend) GetBackendSpec() *BackendSpec {
	if m != nil {
		return m.BackendSpec
	}
	return nil
}

func (m *Backend) GetBackendStatus() *BackendStatus {
	if m != nil {
		return m.BackendStatus
	}
	return nil
}

type BackendSpec struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=Port" json:"Port,omitempty"`
	Priority             int32    `protobuf:"varint,3,opt,name=Priority" json:"Priority,omitempty"`
	Weight               int32    `protobuf:"varint,4,opt,name=Weight" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendSpec) Reset()         { *m = BackendSpec{} }
func (m *BackendSpec) String() string { return proto.CompactTextString(m) }
func (*BackendSpec) ProtoMessage()    {}
func (*BackendSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{9}
}
func (m *BackendSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendSpec.Unmarshal(m, b)
}
func (m *BackendSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendSpec.Marshal(b, m, deterministic)
}
func (dst *BackendSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendSpec.Merge(dst, src)
}
func (m *BackendSpec) XXX_Size() int {
	return xxx_messageInfo_BackendSpec.Size(m)
}
func (m *BackendSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BackendSpec proto.InternalMessageInfo

func (m *BackendSpec) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BackendSpec) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *BackendSpec) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *BackendSpec) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type BackendStatus struct {
	Live                 bool     `protobuf:"varint,1,opt,name=Live" json:"Live,omitempty"`
	TotalConnections     int32    `protobuf:"varint,2,opt,name=TotalConnections" json:"TotalConnections,omitempty"`
	ActiveConnections    int32    `protobuf:"varint,3,opt,name=ActiveConnections" json:"ActiveConnections,omitempty"`
	RefusedConnections   int32    `protobuf:"varint,4,opt,name=RefusedConnections" json:"RefusedConnections,omitempty"`
	Rx                   int32    `protobuf:"varint,5,opt,name=Rx" json:"Rx,omitempty"`
	Tx                   int32    `protobuf:"varint,6,opt,name=Tx" json:"Tx,omitempty"`
	RxSecond             int32    `protobuf:"varint,7,opt,name=RxSecond" json:"RxSecond,omitempty"`
	TxSecond             int32    `protobuf:"varint,8,opt,name=TxSecond" json:"TxSecond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendStatus) Reset()         { *m = BackendStatus{} }
func (m *BackendStatus) String() string { return proto.CompactTextString(m) }
func (*BackendStatus) ProtoMessage()    {}
func (*BackendStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{10}
}
func (m *BackendStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendStatus.Unmarshal(m, b)
}
func (m *BackendStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendStatus.Marshal(b, m, deterministic)
}
func (dst *BackendStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendStatus.Merge(dst, src)
}
func (m *BackendStatus) XXX_Size() int {
	return xxx_messageInfo_BackendStatus.Size(m)
}
func (m *BackendStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BackendStatus proto.InternalMessageInfo

func (m *BackendStatus) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *BackendStatus) GetTotalConnections() int32 {
	if m != nil {
		return m.TotalConnections
	}
	return 0
}

func (m *BackendStatus) GetActiveConnections() int32 {
	if m != nil {
		return m.ActiveConnections
	}
	return 0
}

func (m *BackendStatus) GetRefusedConnections() int32 {
	if m != nil {
		return m.RefusedConnections
	}
	return 0
}

func (m *BackendStatus) GetRx() int32 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *BackendStatus) GetTx() int32 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *BackendStatus) GetRxSecond() int32 {
	if m != nil {
		return m.RxSecond
	}
	return 0
}

func (m *BackendStatus) GetTxSecond() int32 {
	if m != nil {
		return m.TxSecond
	}
	return 0
}

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_native_lb_d6809caa85007f0a, []int{11}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Command)(nil), "proto.Command")
	proto.RegisterType((*Agent)(nil), "proto.Agent")
	proto.RegisterType((*AgentStatus)(nil), "proto.AgentStatus")
	proto.RegisterType((*ServerStats)(nil), "proto.ServerStats")
	proto.RegisterType((*Server)(nil), "proto.Server")
	proto.RegisterType((*Discovery)(nil), "proto.Discovery")
	proto.RegisterType((*HealthCheck)(nil), "proto.HealthCheck")
	proto.RegisterType((*UDP)(nil), "proto.UDP")
	proto.RegisterType((*Backend)(nil), "proto.Backend")
	proto.RegisterType((*BackendSpec)(nil), "proto.BackendSpec")
	proto.RegisterType((*BackendStatus)(nil), "proto.BackendStatus")
	proto.RegisterType((*Result)(nil), "proto.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NativeLoadBalancerAgent service

type NativeLoadBalancerAgentClient interface {
	Connect(ctx context.Context, in *Agent, opts ...grpc.CallOption) (NativeLoadBalancerAgent_ConnectClient, error)
	UpdateAgentStatus(ctx context.Context, in *AgentStatus, opts ...grpc.CallOption) (*Result, error)
	UpdateServerStats(ctx context.Context, in *ServerStats, opts ...grpc.CallOption) (*Result, error)
}

type nativeLoadBalancerAgentClient struct {
	cc *grpc.ClientConn
}

func NewNativeLoadBalancerAgentClient(cc *grpc.ClientConn) NativeLoadBalancerAgentClient {
	return &nativeLoadBalancerAgentClient{cc}
}

func (c *nativeLoadBalancerAgentClient) Connect(ctx context.Context, in *Agent, opts ...grpc.CallOption) (NativeLoadBalancerAgent_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_NativeLoadBalancerAgent_serviceDesc.Streams[0], c.cc, "/proto.NativeLoadBalancerAgent/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &nativeLoadBalancerAgentConnectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NativeLoadBalancerAgent_ConnectClient interface {
	Recv() (*Command, error)
	grpc.ClientStream
}

type nativeLoadBalancerAgentConnectClient struct {
	grpc.ClientStream
}

func (x *nativeLoadBalancerAgentConnectClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nativeLoadBalancerAgentClient) UpdateAgentStatus(ctx context.Context, in *AgentStatus, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/UpdateAgentStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeLoadBalancerAgentClient) UpdateServerStats(ctx context.Context, in *ServerStats, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := grpc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/UpdateServerStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NativeLoadBalancerAgent service

type NativeLoadBalancerAgentServer interface {
	Connect(*Agent, NativeLoadBalancerAgent_ConnectServer) error
	UpdateAgentStatus(context.Context, *AgentStatus) (*Result, error)
	UpdateServerStats(context.Context, *ServerStats) (*Result, error)
}

func RegisterNativeLoadBalancerAgentServer(s *grpc.Server, srv NativeLoadBalancerAgentServer) {
	s.RegisterService(&_NativeLoadBalancerAgent_serviceDesc, srv)
}

func _NativeLoadBalancerAgent_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Agent)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NativeLoadBalancerAgentServer).Connect(m, &nativeLoadBalancerAgentConnectServer{stream})
}

type NativeLoadBalancerAgent_ConnectServer interface {
	Send(*Command) error
	grpc.ServerStream
}

type nativeLoadBalancerAgentConnectServer struct {
	grpc.ServerStream
}

func (x *nativeLoadBalancerAgentConnectServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func _NativeLoadBalancerAgent_UpdateAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).UpdateAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/UpdateAgentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).UpdateAgentStatus(ctx, req.(*AgentStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeLoadBalancerAgent_UpdateServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerStats)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).UpdateServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/UpdateServerStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).UpdateServerStats(ctx, req.(*ServerStats))
	}
	return interceptor(ctx, in, info, handler)
}

var _NativeLoadBalancerAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NativeLoadBalancerAgent",
	HandlerType: (*NativeLoadBalancerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAgentStatus",
			Handler:    _NativeLoadBalancerAgent_UpdateAgentStatus_Handler,
		},
		{
			MethodName: "UpdateServerStats",
			Handler:    _NativeLoadBalancerAgent_UpdateServerStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NativeLoadBalancerAgent_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "native-lb.proto",
}

func init() { proto.RegisterFile("native-lb.proto", fileDescriptor_native_lb_d6809caa85007f0a) }

var fileDescriptor_native_lb_d6809caa85007f0a = []byte{
	// 877 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xcd, 0x8e, 0xdb, 0xb6,
	0x13, 0x8f, 0xec, 0x95, 0x3f, 0xc6, 0xc9, 0xfe, 0x37, 0xfc, 0x07, 0xad, 0x60, 0x04, 0xe8, 0x42,
	0x87, 0x76, 0x91, 0xb6, 0x4e, 0xe0, 0xf6, 0x50, 0xe4, 0xb6, 0x1f, 0x28, 0xb2, 0xc8, 0x26, 0x30,
	0x68, 0xbb, 0x3d, 0xf4, 0xc4, 0x95, 0x18, 0xaf, 0x10, 0x59, 0x74, 0x45, 0xda, 0x70, 0xd0, 0x73,
	0xdf, 0xa1, 0xef, 0xd1, 0x43, 0x81, 0xbe, 0x50, 0x5f, 0xa3, 0x98, 0x21, 0x29, 0x4b, 0x6b, 0x6f,
	0x4f, 0xe2, 0x6f, 0x7e, 0x33, 0xc3, 0xf9, 0xa0, 0x66, 0xe0, 0x7f, 0x85, 0x30, 0xd9, 0x46, 0x7e,
	0x9b, 0xdf, 0x8e, 0x56, 0xa5, 0x32, 0x8a, 0x85, 0xf4, 0x19, 0x7e, 0xb1, 0x50, 0x6a, 0x91, 0xcb,
	0x97, 0x84, 0x6e, 0xd7, 0x1f, 0x5e, 0x9a, 0x6c, 0x29, 0xb5, 0x11, 0xcb, 0x95, 0xd5, 0x8b, 0x6f,
	0xa0, 0x7b, 0xa9, 0x96, 0x4b, 0x51, 0xa4, 0x2c, 0xaa, 0x8e, 0x51, 0x70, 0x1a, 0x9c, 0xf5, 0x79,
	0xc5, 0x7c, 0x05, 0xdd, 0xa9, 0x2c, 0x37, 0xb2, 0xd4, 0x51, 0xeb, 0xb4, 0x7d, 0x36, 0x18, 0x3f,
	0xb1, 0xd6, 0x23, 0x2b, 0xe5, 0x9e, 0x8d, 0x7f, 0x81, 0xf0, 0x7c, 0x21, 0x0b, 0xc3, 0x86, 0xd0,
	0x7b, 0xa3, 0xb4, 0x79, 0x2f, 0x96, 0xd2, 0x39, 0xab, 0x30, 0x7b, 0x0e, 0xfd, 0xeb, 0xc9, 0x79,
	0x9a, 0x96, 0x52, 0xa3, 0x3f, 0x24, 0x77, 0x02, 0x8a, 0x22, 0x5f, 0x6b, 0x23, 0xcb, 0xa8, 0xed,
	0xa2, 0xb0, 0x30, 0xfe, 0x33, 0x80, 0x01, 0x79, 0x9f, 0x1a, 0x61, 0xd6, 0x9a, 0x31, 0x38, 0xaa,
	0xf9, 0xa7, 0x33, 0x3b, 0x81, 0xf6, 0x24, 0x4b, 0xc9, 0x6b, 0xc8, 0xf1, 0x88, 0xb7, 0x4d, 0x8d,
	0x28, 0xcd, 0x2c, 0x5b, 0x4a, 0xe7, 0x71, 0x27, 0x40, 0x1f, 0x44, 0x1c, 0x59, 0x1f, 0x24, 0x1b,
	0x43, 0x67, 0xbe, 0xc2, 0x3a, 0x45, 0xe1, 0x69, 0x70, 0x36, 0x18, 0x0f, 0x47, 0xb6, 0x88, 0x23,
	0x5f, 0xc4, 0xd1, 0xcc, 0x17, 0x91, 0x3b, 0x4d, 0x8c, 0xfa, 0x27, 0x59, 0xea, 0x4c, 0x15, 0x51,
	0xc7, 0x46, 0xed, 0x60, 0xfc, 0x4f, 0x00, 0x03, 0x5b, 0x1e, 0x0c, 0xfb, 0x70, 0xd4, 0xdf, 0xc0,
	0xd3, 0xf3, 0x04, 0xfb, 0x77, 0xa9, 0x8a, 0x42, 0x26, 0x26, 0x53, 0x85, 0x76, 0x39, 0xec, 0x13,
	0x78, 0x17, 0xdf, 0xce, 0x94, 0x11, 0x39, 0xe5, 0x13, 0x72, 0x0f, 0x91, 0x99, 0x39, 0xe6, 0xc8,
	0x32, 0x0e, 0x62, 0x3f, 0xf8, 0x76, 0x2a, 0x13, 0x55, 0xa4, 0x94, 0x55, 0xc8, 0x2b, 0x8c, 0xdc,
	0xcc, 0x73, 0x1d, 0xcb, 0x79, 0xcc, 0x5e, 0x40, 0xef, 0x42, 0x24, 0x1f, 0x65, 0x91, 0xea, 0xa8,
	0x4b, 0xad, 0x3f, 0x76, 0xad, 0x77, 0x62, 0x5e, 0xf1, 0xf1, 0x1f, 0x6d, 0xe8, 0xd8, 0x4c, 0x31,
	0xc9, 0x8b, 0xac, 0x7a, 0x47, 0x74, 0xc6, 0x6b, 0x26, 0x68, 0x99, 0xa8, 0xdc, 0x75, 0xbd, 0xc2,
	0xec, 0x39, 0xb4, 0xe7, 0x57, 0x13, 0x4a, 0x67, 0x30, 0x06, 0x77, 0xc3, 0xfc, 0x6a, 0xc2, 0x51,
	0x8c, 0x69, 0x5d, 0x88, 0x5c, 0x14, 0x89, 0xef, 0x93, 0x87, 0xec, 0x4b, 0x38, 0x7e, 0x27, 0xb6,
	0xf5, 0xaa, 0x85, 0xa4, 0x70, 0x4f, 0x8a, 0x05, 0xbe, 0xcc, 0x33, 0x59, 0x98, 0xeb, 0x34, 0x97,
	0xd8, 0x3d, 0xb5, 0x36, 0xae, 0x51, 0xfb, 0x04, 0x1b, 0x01, 0x73, 0x49, 0xd5, 0xd5, 0xbb, 0xa4,
	0x7e, 0x80, 0x61, 0xaf, 0x21, 0x72, 0xd2, 0xdd, 0x9d, 0xde, 0xaa, 0x47, 0x56, 0x0f, 0xf2, 0x6c,
	0x04, 0xfd, 0xab, 0x4c, 0x27, 0x6a, 0x23, 0xcb, 0x4f, 0x51, 0x9f, 0xf2, 0x3f, 0x71, 0xf9, 0x57,
	0x72, 0xbe, 0x53, 0x61, 0xdf, 0xc3, 0xe0, 0x8d, 0x14, 0xb9, 0xb9, 0xbb, 0xbc, 0x93, 0xc9, 0xc7,
	0x08, 0xc8, 0x82, 0x39, 0x8b, 0x1a, 0xc3, 0xeb, 0x6a, 0xf1, 0xbc, 0x76, 0x0b, 0x36, 0xe7, 0x6d,
	0xad, 0x39, 0x78, 0x46, 0xb7, 0x2e, 0xc4, 0xe9, 0x4a, 0x26, 0xee, 0x2f, 0x67, 0xcd, 0x56, 0x23,
	0xc3, 0xeb, 0x6a, 0xf1, 0x5f, 0x41, 0x23, 0x1a, 0xf6, 0x0c, 0xc2, 0x1f, 0x45, 0x96, 0x6b, 0x72,
	0x1d, 0x72, 0x0b, 0xd8, 0x67, 0xd0, 0x99, 0x08, 0xad, 0xa5, 0x7f, 0xd2, 0x0e, 0xe1, 0x83, 0xb8,
	0x2e, 0x8c, 0x2c, 0x37, 0xee, 0x21, 0xf7, 0x79, 0x85, 0xe9, 0x25, 0xbb, 0x0a, 0xba, 0x96, 0xfb,
	0x82, 0xf9, 0xe8, 0xc3, 0x5a, 0xf4, 0xaf, 0xe0, 0xff, 0x93, 0xac, 0x58, 0x38, 0x95, 0xab, 0x75,
	0x29, 0xcc, 0xee, 0x4f, 0x3c, 0x44, 0xc5, 0x6f, 0xe9, 0xc1, 0xb1, 0x53, 0x18, 0xbc, 0x13, 0x5b,
	0x2e, 0x7f, 0x5d, 0x4b, 0x6d, 0x7c, 0xd8, 0x75, 0x11, 0x8b, 0xe1, 0x31, 0x41, 0xbd, 0x52, 0xc5,
	0x2e, 0x85, 0x86, 0x2c, 0xfe, 0x0d, 0xdf, 0x27, 0x55, 0xe5, 0x7e, 0x1d, 0x83, 0x46, 0x7b, 0x1e,
	0xaa, 0x23, 0x7b, 0x0d, 0x4f, 0x3c, 0xa4, 0xd1, 0x46, 0xb7, 0x0c, 0xc6, 0xcf, 0xee, 0xd9, 0x11,
	0xc7, 0x9b, 0xaa, 0x71, 0xd6, 0xb8, 0x11, 0xcb, 0x83, 0x83, 0xd6, 0x37, 0x17, 0xcf, 0x28, 0x9b,
	0xa8, 0xd2, 0xb8, 0xbf, 0x8e, 0xce, 0xf6, 0x6f, 0xcc, 0x54, 0x99, 0x99, 0x4f, 0x6e, 0x8a, 0x54,
	0x18, 0x1b, 0xf6, 0xb3, 0xcc, 0x16, 0x77, 0xc6, 0x4d, 0x11, 0x87, 0xe2, 0xdf, 0x5b, 0xf7, 0xe2,
	0x44, 0xcf, 0x37, 0xd9, 0xc6, 0x0e, 0xb3, 0x1e, 0xa7, 0x33, 0x7b, 0x01, 0x27, 0x34, 0x73, 0xf6,
	0x67, 0xd9, 0x9e, 0xfc, 0xf0, 0xe0, 0x6b, 0x3f, 0x34, 0xf8, 0x46, 0xc0, 0xb8, 0xfc, 0xb0, 0xd6,
	0x32, 0xad, 0xab, 0xdb, 0x18, 0x0f, 0x30, 0xec, 0x18, 0x5a, 0x7c, 0xeb, 0xc6, 0x5d, 0x8b, 0x6f,
	0x11, 0xcf, 0xb6, 0x6e, 0xc4, 0xb5, 0x66, 0xdb, 0xc6, 0x50, 0xec, 0xfe, 0xc7, 0x50, 0xec, 0x35,
	0x87, 0x62, 0xdc, 0x83, 0x0e, 0x97, 0x7a, 0x9d, 0x9b, 0xf1, 0xdf, 0x01, 0x7c, 0xfe, 0x9e, 0x36,
	0xef, 0x8d, 0x12, 0xa9, 0x9b, 0x4a, 0xa5, 0x5d, 0x81, 0x5f, 0xe3, 0x3a, 0xa5, 0x60, 0xd8, 0x63,
	0xd7, 0x48, 0x22, 0x86, 0x7e, 0x82, 0xba, 0xed, 0x1a, 0x3f, 0x7a, 0x15, 0xb0, 0x1f, 0xe0, 0xe9,
	0x7c, 0x95, 0x0a, 0x23, 0x1b, 0x0b, 0xae, 0x6e, 0x66, 0x65, 0x43, 0xbf, 0x79, 0x6d, 0x00, 0xf1,
	0xa3, 0x9d, 0x65, 0x63, 0xc9, 0x34, 0xf6, 0x33, 0xc9, 0xf6, 0x2c, 0x6f, 0x3b, 0x84, 0xbf, 0xfb,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x81, 0xf1, 0x4c, 0x3c, 0x08, 0x00, 0x00,
}
