#!/bin/bash

make docker-build

kubectl apply -f config/crds/
kubectl apply -f config/rbac/rbac_role_binding.yaml

kubectl apply -f config/samples/cluster_internal.yaml
kubectl apply -f config/samples/cluster_external.yaml

kubectl apply -f config/ci/nativelb-configmap.yaml

kubectl apply -f config/app/nativelb-controller.yaml
kubectl apply -f config/app/nativelb-agent.yaml

sleep 10

timeout 2m ci/wait-pods-ok

kubectl get all --all-namespaces -o wide

kubectl get events --all-namespaces

kubectl get nodes -o wide

docker ps -a