#!/bin/bash

kubectl apply -f config/crds/
kubectl apply -f config/samples/cluster_internal_develop.yaml
kubectl apply -f config/rbac/rbac_role_binding.yaml
kubectl apply -f config/controller/nativelb-controller.yaml

timeout 2m ci/wait-pods-ok

kubectl get pod --all-namespaces -o wide

kubectl get events --all-namespaces

kubectl get nodes -o wide