// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/native-lb.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Data struct {
	Servers              []*Server `protobuf:"bytes,1,rep,name=Servers,proto3" json:"Servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

type Agent struct {
	HostName             string   `protobuf:"bytes,1,opt,name=HostName,proto3" json:"HostName,omitempty"`
	IPAddress            string   `protobuf:"bytes,2,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	Cluster              string   `protobuf:"bytes,3,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{1}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Agent) GetIPAddress() string {
	if m != nil {
		return m.IPAddress
	}
	return ""
}

func (m *Agent) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

type AgentStatus struct {
	Name                 string             `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Pid                  int32              `protobuf:"varint,2,opt,name=Pid,proto3" json:"Pid,omitempty"`
	StartTime            string             `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	Time                 string             `protobuf:"bytes,4,opt,name=Time,proto3" json:"Time,omitempty"`
	Uptime               *duration.Duration `protobuf:"bytes,5,opt,name=Uptime,proto3" json:"Uptime,omitempty"`
	Version              string             `protobuf:"bytes,6,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AgentStatus) Reset()         { *m = AgentStatus{} }
func (m *AgentStatus) String() string { return proto.CompactTextString(m) }
func (*AgentStatus) ProtoMessage()    {}
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{2}
}

func (m *AgentStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentStatus.Unmarshal(m, b)
}
func (m *AgentStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentStatus.Marshal(b, m, deterministic)
}
func (m *AgentStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentStatus.Merge(m, src)
}
func (m *AgentStatus) XXX_Size() int {
	return xxx_messageInfo_AgentStatus.Size(m)
}
func (m *AgentStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentStatus.DiscardUnknown(m)
}

var xxx_messageInfo_AgentStatus proto.InternalMessageInfo

func (m *AgentStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentStatus) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *AgentStatus) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *AgentStatus) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *AgentStatus) GetUptime() *duration.Duration {
	if m != nil {
		return m.Uptime
	}
	return nil
}

func (m *AgentStatus) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ServerStats struct {
	Name                 string     `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ActiveConnections    int32      `protobuf:"varint,2,opt,name=ActiveConnections,proto3" json:"ActiveConnections,omitempty"`
	RxTotal              int32      `protobuf:"varint,3,opt,name=RxTotal,proto3" json:"RxTotal,omitempty"`
	TxTotal              int32      `protobuf:"varint,4,opt,name=TxTotal,proto3" json:"TxTotal,omitempty"`
	RxSecond             int32      `protobuf:"varint,5,opt,name=RxSecond,proto3" json:"RxSecond,omitempty"`
	TxSecond             int32      `protobuf:"varint,6,opt,name=TxSecond,proto3" json:"TxSecond,omitempty"`
	Backends             []*Backend `protobuf:"bytes,7,rep,name=Backends,proto3" json:"Backends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServerStats) Reset()         { *m = ServerStats{} }
func (m *ServerStats) String() string { return proto.CompactTextString(m) }
func (*ServerStats) ProtoMessage()    {}
func (*ServerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{3}
}

func (m *ServerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerStats.Unmarshal(m, b)
}
func (m *ServerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerStats.Marshal(b, m, deterministic)
}
func (m *ServerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerStats.Merge(m, src)
}
func (m *ServerStats) XXX_Size() int {
	return xxx_messageInfo_ServerStats.Size(m)
}
func (m *ServerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ServerStats proto.InternalMessageInfo

func (m *ServerStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServerStats) GetActiveConnections() int32 {
	if m != nil {
		return m.ActiveConnections
	}
	return 0
}

func (m *ServerStats) GetRxTotal() int32 {
	if m != nil {
		return m.RxTotal
	}
	return 0
}

func (m *ServerStats) GetTxTotal() int32 {
	if m != nil {
		return m.TxTotal
	}
	return 0
}

func (m *ServerStats) GetRxSecond() int32 {
	if m != nil {
		return m.RxSecond
	}
	return 0
}

func (m *ServerStats) GetTxSecond() int32 {
	if m != nil {
		return m.TxSecond
	}
	return 0
}

func (m *ServerStats) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

type Server struct {
	Bind                     string       `protobuf:"bytes,1,opt,name=Bind,proto3" json:"Bind,omitempty"`
	Protocol                 string       `protobuf:"bytes,2,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	UDP                      *UDP         `protobuf:"bytes,3,opt,name=UDP,proto3" json:"UDP,omitempty"`
	Balance                  string       `protobuf:"bytes,4,opt,name=Balance,proto3" json:"Balance,omitempty"`
	MaxConnections           int32        `protobuf:"varint,5,opt,name=MaxConnections,proto3" json:"MaxConnections,omitempty"`
	ClientIdleTimeout        string       `protobuf:"bytes,6,opt,name=ClientIdleTimeout,proto3" json:"ClientIdleTimeout,omitempty"`
	BackendIdleTimeout       string       `protobuf:"bytes,7,opt,name=BackendIdleTimeout,proto3" json:"BackendIdleTimeout,omitempty"`
	BackendConnectionTimeout string       `protobuf:"bytes,8,opt,name=BackendConnectionTimeout,proto3" json:"BackendConnectionTimeout,omitempty"`
	Discovery                *Discovery   `protobuf:"bytes,9,opt,name=Discovery,proto3" json:"Discovery,omitempty"`
	HealthCheck              *HealthCheck `protobuf:"bytes,10,opt,name=HealthCheck,proto3" json:"HealthCheck,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}     `json:"-"`
	XXX_unrecognized         []byte       `json:"-"`
	XXX_sizecache            int32        `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{4}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *Server) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Server) GetUDP() *UDP {
	if m != nil {
		return m.UDP
	}
	return nil
}

func (m *Server) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *Server) GetMaxConnections() int32 {
	if m != nil {
		return m.MaxConnections
	}
	return 0
}

func (m *Server) GetClientIdleTimeout() string {
	if m != nil {
		return m.ClientIdleTimeout
	}
	return ""
}

func (m *Server) GetBackendIdleTimeout() string {
	if m != nil {
		return m.BackendIdleTimeout
	}
	return ""
}

func (m *Server) GetBackendConnectionTimeout() string {
	if m != nil {
		return m.BackendConnectionTimeout
	}
	return ""
}

func (m *Server) GetDiscovery() *Discovery {
	if m != nil {
		return m.Discovery
	}
	return nil
}

func (m *Server) GetHealthCheck() *HealthCheck {
	if m != nil {
		return m.HealthCheck
	}
	return nil
}

type Discovery struct {
	Kind                 string         `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	BackendSpec          []*BackendSpec `protobuf:"bytes,2,rep,name=BackendSpec,proto3" json:"BackendSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Discovery) Reset()         { *m = Discovery{} }
func (m *Discovery) String() string { return proto.CompactTextString(m) }
func (*Discovery) ProtoMessage()    {}
func (*Discovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{5}
}

func (m *Discovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discovery.Unmarshal(m, b)
}
func (m *Discovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discovery.Marshal(b, m, deterministic)
}
func (m *Discovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discovery.Merge(m, src)
}
func (m *Discovery) XXX_Size() int {
	return xxx_messageInfo_Discovery.Size(m)
}
func (m *Discovery) XXX_DiscardUnknown() {
	xxx_messageInfo_Discovery.DiscardUnknown(m)
}

var xxx_messageInfo_Discovery proto.InternalMessageInfo

func (m *Discovery) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Discovery) GetBackendSpec() []*BackendSpec {
	if m != nil {
		return m.BackendSpec
	}
	return nil
}

type HealthCheck struct {
	Fails                int32    `protobuf:"varint,1,opt,name=Fails,proto3" json:"Fails,omitempty"`
	Passes               int32    `protobuf:"varint,2,opt,name=Passes,proto3" json:"Passes,omitempty"`
	Interval             string   `protobuf:"bytes,3,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Timeout              string   `protobuf:"bytes,4,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Kind                 string   `protobuf:"bytes,5,opt,name=Kind,proto3" json:"Kind,omitempty"`
	PingTimeoutDuration  string   `protobuf:"bytes,6,opt,name=PingTimeoutDuration,proto3" json:"PingTimeoutDuration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{6}
}

func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (m *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(m, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func (m *HealthCheck) GetFails() int32 {
	if m != nil {
		return m.Fails
	}
	return 0
}

func (m *HealthCheck) GetPasses() int32 {
	if m != nil {
		return m.Passes
	}
	return 0
}

func (m *HealthCheck) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *HealthCheck) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *HealthCheck) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *HealthCheck) GetPingTimeoutDuration() string {
	if m != nil {
		return m.PingTimeoutDuration
	}
	return ""
}

type UDP struct {
	MaxRequests          int32    `protobuf:"varint,1,opt,name=MaxRequests,proto3" json:"MaxRequests,omitempty"`
	MaxResponses         int32    `protobuf:"varint,2,opt,name=MaxResponses,proto3" json:"MaxResponses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UDP) Reset()         { *m = UDP{} }
func (m *UDP) String() string { return proto.CompactTextString(m) }
func (*UDP) ProtoMessage()    {}
func (*UDP) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{7}
}

func (m *UDP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UDP.Unmarshal(m, b)
}
func (m *UDP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UDP.Marshal(b, m, deterministic)
}
func (m *UDP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UDP.Merge(m, src)
}
func (m *UDP) XXX_Size() int {
	return xxx_messageInfo_UDP.Size(m)
}
func (m *UDP) XXX_DiscardUnknown() {
	xxx_messageInfo_UDP.DiscardUnknown(m)
}

var xxx_messageInfo_UDP proto.InternalMessageInfo

func (m *UDP) GetMaxRequests() int32 {
	if m != nil {
		return m.MaxRequests
	}
	return 0
}

func (m *UDP) GetMaxResponses() int32 {
	if m != nil {
		return m.MaxResponses
	}
	return 0
}

type Backend struct {
	BackendSpec          *BackendSpec   `protobuf:"bytes,1,opt,name=BackendSpec,proto3" json:"BackendSpec,omitempty"`
	BackendStatus        *BackendStatus `protobuf:"bytes,2,opt,name=BackendStatus,proto3" json:"BackendStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Backend) Reset()         { *m = Backend{} }
func (m *Backend) String() string { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()    {}
func (*Backend) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{8}
}

func (m *Backend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backend.Unmarshal(m, b)
}
func (m *Backend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backend.Marshal(b, m, deterministic)
}
func (m *Backend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backend.Merge(m, src)
}
func (m *Backend) XXX_Size() int {
	return xxx_messageInfo_Backend.Size(m)
}
func (m *Backend) XXX_DiscardUnknown() {
	xxx_messageInfo_Backend.DiscardUnknown(m)
}

var xxx_messageInfo_Backend proto.InternalMessageInfo

func (m *Backend) GetBackendSpec() *BackendSpec {
	if m != nil {
		return m.BackendSpec
	}
	return nil
}

func (m *Backend) GetBackendStatus() *BackendStatus {
	if m != nil {
		return m.BackendStatus
	}
	return nil
}

type BackendSpec struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=Port,proto3" json:"Port,omitempty"`
	Priority             int32    `protobuf:"varint,3,opt,name=Priority,proto3" json:"Priority,omitempty"`
	Weight               int32    `protobuf:"varint,4,opt,name=Weight,proto3" json:"Weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendSpec) Reset()         { *m = BackendSpec{} }
func (m *BackendSpec) String() string { return proto.CompactTextString(m) }
func (*BackendSpec) ProtoMessage()    {}
func (*BackendSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{9}
}

func (m *BackendSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendSpec.Unmarshal(m, b)
}
func (m *BackendSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendSpec.Marshal(b, m, deterministic)
}
func (m *BackendSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendSpec.Merge(m, src)
}
func (m *BackendSpec) XXX_Size() int {
	return xxx_messageInfo_BackendSpec.Size(m)
}
func (m *BackendSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendSpec.DiscardUnknown(m)
}

var xxx_messageInfo_BackendSpec proto.InternalMessageInfo

func (m *BackendSpec) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BackendSpec) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *BackendSpec) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *BackendSpec) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type BackendStatus struct {
	Live                 bool     `protobuf:"varint,1,opt,name=Live,proto3" json:"Live,omitempty"`
	TotalConnections     int32    `protobuf:"varint,2,opt,name=TotalConnections,proto3" json:"TotalConnections,omitempty"`
	ActiveConnections    int32    `protobuf:"varint,3,opt,name=ActiveConnections,proto3" json:"ActiveConnections,omitempty"`
	RefusedConnections   int32    `protobuf:"varint,4,opt,name=RefusedConnections,proto3" json:"RefusedConnections,omitempty"`
	Rx                   int32    `protobuf:"varint,5,opt,name=Rx,proto3" json:"Rx,omitempty"`
	Tx                   int32    `protobuf:"varint,6,opt,name=Tx,proto3" json:"Tx,omitempty"`
	RxSecond             int32    `protobuf:"varint,7,opt,name=RxSecond,proto3" json:"RxSecond,omitempty"`
	TxSecond             int32    `protobuf:"varint,8,opt,name=TxSecond,proto3" json:"TxSecond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BackendStatus) Reset()         { *m = BackendStatus{} }
func (m *BackendStatus) String() string { return proto.CompactTextString(m) }
func (*BackendStatus) ProtoMessage()    {}
func (*BackendStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{10}
}

func (m *BackendStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackendStatus.Unmarshal(m, b)
}
func (m *BackendStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackendStatus.Marshal(b, m, deterministic)
}
func (m *BackendStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackendStatus.Merge(m, src)
}
func (m *BackendStatus) XXX_Size() int {
	return xxx_messageInfo_BackendStatus.Size(m)
}
func (m *BackendStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BackendStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BackendStatus proto.InternalMessageInfo

func (m *BackendStatus) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *BackendStatus) GetTotalConnections() int32 {
	if m != nil {
		return m.TotalConnections
	}
	return 0
}

func (m *BackendStatus) GetActiveConnections() int32 {
	if m != nil {
		return m.ActiveConnections
	}
	return 0
}

func (m *BackendStatus) GetRefusedConnections() int32 {
	if m != nil {
		return m.RefusedConnections
	}
	return 0
}

func (m *BackendStatus) GetRx() int32 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *BackendStatus) GetTx() int32 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *BackendStatus) GetRxSecond() int32 {
	if m != nil {
		return m.RxSecond
	}
	return 0
}

func (m *BackendStatus) GetTxSecond() int32 {
	if m != nil {
		return m.TxSecond
	}
	return 0
}

type Command struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{11}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_6db544c34c107aae, []int{12}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Data)(nil), "proto.Data")
	proto.RegisterType((*Agent)(nil), "proto.Agent")
	proto.RegisterType((*AgentStatus)(nil), "proto.AgentStatus")
	proto.RegisterType((*ServerStats)(nil), "proto.ServerStats")
	proto.RegisterType((*Server)(nil), "proto.Server")
	proto.RegisterType((*Discovery)(nil), "proto.Discovery")
	proto.RegisterType((*HealthCheck)(nil), "proto.HealthCheck")
	proto.RegisterType((*UDP)(nil), "proto.UDP")
	proto.RegisterType((*Backend)(nil), "proto.Backend")
	proto.RegisterType((*BackendSpec)(nil), "proto.BackendSpec")
	proto.RegisterType((*BackendStatus)(nil), "proto.BackendStatus")
	proto.RegisterType((*Command)(nil), "proto.Command")
	proto.RegisterType((*Result)(nil), "proto.Result")
}

func init() { proto.RegisterFile("proto/native-lb.proto", fileDescriptor_6db544c34c107aae) }

var fileDescriptor_6db544c34c107aae = []byte{
	// 890 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x5e, 0xdb, 0x19, 0xff, 0xd4, 0x90, 0x28, 0x34, 0x0b, 0x0c, 0xd1, 0x0a, 0x45, 0x73, 0x80,
	0x68, 0xc5, 0x3a, 0x60, 0x10, 0x87, 0xbd, 0x25, 0xb6, 0x60, 0xa3, 0xfd, 0x91, 0xd5, 0xb6, 0xe1,
	0xc0, 0xa9, 0x33, 0xd3, 0xeb, 0x8c, 0x76, 0x32, 0x6d, 0xa6, 0xdb, 0x96, 0x23, 0xce, 0xbc, 0x02,
	0xe2, 0x39, 0xb8, 0xf0, 0x48, 0xbc, 0x06, 0xaa, 0xee, 0x6a, 0x7b, 0x26, 0xb1, 0x11, 0x7b, 0x9a,
	0xfe, 0xea, 0xab, 0xae, 0xae, 0xaa, 0xaf, 0xa7, 0x1a, 0x3e, 0x5e, 0x94, 0xca, 0xa8, 0xf3, 0x42,
	0x98, 0x6c, 0x25, 0x9f, 0xe5, 0xd7, 0x7d, 0x8b, 0x59, 0x60, 0x3f, 0x27, 0x9f, 0xcf, 0x95, 0x9a,
	0xe7, 0xf2, 0xdc, 0xa2, 0xeb, 0xe5, 0xdb, 0xf3, 0x74, 0x59, 0x0a, 0x93, 0xa9, 0xc2, 0xb9, 0xc5,
	0xe7, 0x70, 0x30, 0x12, 0x46, 0xb0, 0x2f, 0xa1, 0x33, 0x91, 0xe5, 0x4a, 0x96, 0x3a, 0x6a, 0x9c,
	0xb6, 0xce, 0xc2, 0xc1, 0xa1, 0x73, 0xe8, 0x3b, 0x2b, 0xf7, 0x6c, 0xfc, 0x0b, 0x04, 0x17, 0x73,
	0x59, 0x18, 0x76, 0x02, 0xdd, 0x17, 0x4a, 0x9b, 0x37, 0xe2, 0x56, 0x46, 0x8d, 0xd3, 0xc6, 0x59,
	0x8f, 0x6f, 0x30, 0x7b, 0x02, 0xbd, 0xab, 0xf1, 0x45, 0x9a, 0x96, 0x52, 0xeb, 0xa8, 0x69, 0xc9,
	0xad, 0x81, 0x45, 0xd0, 0x19, 0xe6, 0x4b, 0x6d, 0x64, 0x19, 0xb5, 0x2c, 0xe7, 0x61, 0xfc, 0x57,
	0x03, 0x42, 0x1b, 0x7d, 0x62, 0x84, 0x59, 0x6a, 0xc6, 0xe0, 0xa0, 0x12, 0xdf, 0xae, 0xd9, 0x31,
	0xb4, 0xc6, 0x59, 0x6a, 0xa3, 0x06, 0x1c, 0x97, 0x78, 0xda, 0xc4, 0x88, 0xd2, 0x4c, 0xb3, 0x5b,
	0x49, 0x11, 0xb7, 0x06, 0x8c, 0x61, 0x89, 0x03, 0x17, 0xc3, 0xda, 0xbe, 0x81, 0xf6, 0x6c, 0x61,
	0xd0, 0x1a, 0x9c, 0x36, 0xce, 0xc2, 0xc1, 0x67, 0x7d, 0xd7, 0xa6, 0xbe, 0x6f, 0x53, 0x7f, 0x44,
	0x6d, 0xe2, 0xe4, 0x88, 0x49, 0xff, 0x24, 0x4b, 0x9d, 0xa9, 0x22, 0x6a, 0xbb, 0xa4, 0x09, 0xc6,
	0xff, 0x34, 0x20, 0x74, 0xdd, 0xc1, 0xac, 0x77, 0x27, 0xfd, 0x15, 0x7c, 0x78, 0x91, 0xa0, 0x40,
	0x43, 0x55, 0x14, 0x32, 0xc1, 0xc8, 0x9a, 0x4a, 0x78, 0x48, 0xe0, 0x59, 0x7c, 0x3d, 0x55, 0x46,
	0xe4, 0xb6, 0x9c, 0x80, 0x7b, 0x88, 0xcc, 0x94, 0x98, 0x03, 0xc7, 0x10, 0x44, 0x39, 0xf8, 0x7a,
	0x22, 0x13, 0x55, 0xa4, 0xb6, 0xa8, 0x80, 0x6f, 0x30, 0x72, 0x53, 0xcf, 0xb5, 0x1d, 0xe7, 0x31,
	0x7b, 0x0a, 0xdd, 0x4b, 0x91, 0xbc, 0x93, 0x45, 0xaa, 0xa3, 0x8e, 0x55, 0xfe, 0x88, 0x94, 0x27,
	0x33, 0xdf, 0xf0, 0xf1, 0x9f, 0x2d, 0x68, 0xbb, 0x4a, 0xb1, 0xc8, 0xcb, 0xac, 0x48, 0x7d, 0x91,
	0xb8, 0xc6, 0x63, 0xc6, 0xb8, 0x33, 0x51, 0x39, 0x89, 0xbe, 0xc1, 0xec, 0x09, 0xb4, 0x66, 0xa3,
	0xb1, 0x2d, 0x27, 0x1c, 0x00, 0x9d, 0x30, 0x1b, 0x8d, 0x39, 0x9a, 0xb1, 0xac, 0x4b, 0x91, 0x8b,
	0x22, 0xf1, 0x32, 0x79, 0xc8, 0xbe, 0x80, 0xa3, 0xd7, 0x62, 0x5d, 0xed, 0x9a, 0x2b, 0xee, 0x9e,
	0x15, 0x1b, 0x3c, 0xcc, 0x33, 0x59, 0x98, 0xab, 0x34, 0x97, 0xa8, 0xb1, 0x5a, 0x1a, 0x12, 0xea,
	0x21, 0xc1, 0xfa, 0xc0, 0xa8, 0xa8, 0xaa, 0x7b, 0xc7, 0xba, 0xef, 0x60, 0xd8, 0x73, 0x88, 0xc8,
	0xba, 0x3d, 0xd3, 0xef, 0xea, 0xda, 0x5d, 0x7b, 0x79, 0xd6, 0x87, 0xde, 0x28, 0xd3, 0x89, 0x5a,
	0xc9, 0xf2, 0x2e, 0xea, 0xd9, 0xfa, 0x8f, 0xa9, 0xfe, 0x8d, 0x9d, 0x6f, 0x5d, 0xd8, 0x77, 0x10,
	0xbe, 0x90, 0x22, 0x37, 0x37, 0xc3, 0x1b, 0x99, 0xbc, 0x8b, 0xc0, 0xee, 0x60, 0xb4, 0xa3, 0xc2,
	0xf0, 0xaa, 0x5b, 0x3c, 0xab, 0x9c, 0x82, 0xe2, 0xbc, 0xac, 0x88, 0x83, 0x6b, 0x0c, 0x4b, 0x29,
	0x4e, 0x16, 0x32, 0x89, 0x9a, 0x56, 0x6a, 0x56, 0x97, 0x1a, 0x19, 0x5e, 0x75, 0x8b, 0xff, 0x6e,
	0xd4, 0xb2, 0x61, 0x8f, 0x21, 0xf8, 0x41, 0x64, 0xb9, 0xb6, 0xa1, 0x03, 0xee, 0x00, 0xfb, 0x04,
	0xda, 0x63, 0xa1, 0xb5, 0xf4, 0x57, 0x9a, 0x10, 0x5e, 0x88, 0xab, 0xc2, 0xc8, 0x72, 0x45, 0x17,
	0xb9, 0xc7, 0x37, 0xd8, 0xde, 0x64, 0xea, 0x20, 0x49, 0xee, 0x1b, 0xe6, 0xb3, 0x0f, 0x2a, 0xd9,
	0x7f, 0x0d, 0x1f, 0x8d, 0xb3, 0x62, 0x4e, 0x2e, 0xfe, 0xe7, 0x24, 0x81, 0x77, 0x51, 0xf1, 0x4b,
	0x7b, 0xe1, 0xd8, 0x29, 0x84, 0xaf, 0xc5, 0x9a, 0xcb, 0x5f, 0x97, 0x52, 0x1b, 0x9f, 0x76, 0xd5,
	0xc4, 0x62, 0xf8, 0xc0, 0x42, 0xbd, 0x50, 0xc5, 0xb6, 0x84, 0x9a, 0x2d, 0xfe, 0x0d, 0xef, 0xa7,
	0xed, 0xca, 0xfd, 0x3e, 0x36, 0x6a, 0xf2, 0xec, 0xeb, 0x23, 0x7b, 0x0e, 0x87, 0x1e, 0xda, 0xc9,
	0x66, 0x4f, 0x09, 0x07, 0x8f, 0xef, 0xed, 0xb3, 0x1c, 0xaf, 0xbb, 0xc6, 0x59, 0xed, 0x44, 0x6c,
	0x0f, 0xce, 0x59, 0x2f, 0x2e, 0xae, 0xd1, 0x36, 0x56, 0xa5, 0xa1, 0xbf, 0xce, 0xae, 0xdd, 0xdf,
	0x98, 0xa9, 0x32, 0x33, 0x77, 0x34, 0x45, 0x36, 0x18, 0x05, 0xfb, 0x59, 0x66, 0xf3, 0x1b, 0x43,
	0x53, 0x84, 0x50, 0xfc, 0x7b, 0xf3, 0x5e, 0x9e, 0x18, 0xf9, 0x55, 0xb6, 0x72, 0xc3, 0xac, 0xcb,
	0xed, 0x9a, 0x3d, 0x85, 0x63, 0x3b, 0x73, 0x1e, 0xce, 0xb2, 0x07, 0xf6, 0xdd, 0x83, 0xaf, 0xb5,
	0x6f, 0xf0, 0xf5, 0x81, 0x71, 0xf9, 0x76, 0xa9, 0x65, 0x5a, 0x75, 0x77, 0x39, 0xee, 0x60, 0xd8,
	0x11, 0x34, 0xf9, 0x9a, 0x26, 0x42, 0x93, 0xaf, 0x11, 0x4f, 0xd7, 0x34, 0xe2, 0x9a, 0xd3, 0x75,
	0x6d, 0x28, 0x76, 0xfe, 0x63, 0x28, 0x76, 0xeb, 0x43, 0x31, 0xee, 0x41, 0x67, 0xa8, 0x6e, 0x6f,
	0x45, 0x91, 0xc6, 0x5d, 0x68, 0x73, 0xa9, 0x97, 0xb9, 0x19, 0xfc, 0xd1, 0x84, 0x4f, 0xdf, 0xd8,
	0x57, 0xf6, 0x95, 0x12, 0x29, 0x0d, 0xa8, 0xd2, 0x3d, 0x86, 0xcf, 0xe0, 0x70, 0x58, 0x4a, 0x61,
	0x24, 0x3d, 0x93, 0x2c, 0xf4, 0xbf, 0xb8, 0x30, 0xe2, 0xc4, 0xbf, 0xa5, 0x2e, 0x50, 0xfc, 0x08,
	0xdd, 0x67, 0x8b, 0xf4, 0x7d, 0xdc, 0x47, 0x32, 0x97, 0xff, 0xd7, 0xfd, 0x7b, 0x38, 0xfa, 0x51,
	0x9a, 0xea, 0x3b, 0xea, 0x47, 0x3a, 0x15, 0x75, 0xe2, 0xef, 0x6b, 0xc5, 0x67, 0xb3, 0xaf, 0xfa,
	0x94, 0xed, 0xdb, 0x57, 0xf1, 0x89, 0x1f, 0x5d, 0xb7, 0xad, 0xf1, 0xdb, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0x48, 0x5b, 0x0c, 0x8a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NativeLoadBalancerAgentClient is the client API for NativeLoadBalancerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NativeLoadBalancerAgentClient interface {
	CreateServers(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
	UpdateServers(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
	DeleteServers(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error)
	GetAgentStatus(ctx context.Context, in *Command, opts ...grpc.CallOption) (*AgentStatus, error)
	GetServerStats(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ServerStats, error)
}

type nativeLoadBalancerAgentClient struct {
	cc *grpc.ClientConn
}

func NewNativeLoadBalancerAgentClient(cc *grpc.ClientConn) NativeLoadBalancerAgentClient {
	return &nativeLoadBalancerAgentClient{cc}
}

func (c *nativeLoadBalancerAgentClient) CreateServers(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/CreateServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeLoadBalancerAgentClient) UpdateServers(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/UpdateServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeLoadBalancerAgentClient) DeleteServers(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/DeleteServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeLoadBalancerAgentClient) GetAgentStatus(ctx context.Context, in *Command, opts ...grpc.CallOption) (*AgentStatus, error) {
	out := new(AgentStatus)
	err := c.cc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/GetAgentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nativeLoadBalancerAgentClient) GetServerStats(ctx context.Context, in *Command, opts ...grpc.CallOption) (*ServerStats, error) {
	out := new(ServerStats)
	err := c.cc.Invoke(ctx, "/proto.NativeLoadBalancerAgent/GetServerStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NativeLoadBalancerAgentServer is the server API for NativeLoadBalancerAgent service.
type NativeLoadBalancerAgentServer interface {
	CreateServers(context.Context, *Data) (*Result, error)
	UpdateServers(context.Context, *Data) (*Result, error)
	DeleteServers(context.Context, *Data) (*Result, error)
	GetAgentStatus(context.Context, *Command) (*AgentStatus, error)
	GetServerStats(context.Context, *Command) (*ServerStats, error)
}

func RegisterNativeLoadBalancerAgentServer(s *grpc.Server, srv NativeLoadBalancerAgentServer) {
	s.RegisterService(&_NativeLoadBalancerAgent_serviceDesc, srv)
}

func _NativeLoadBalancerAgent_CreateServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).CreateServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/CreateServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).CreateServers(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeLoadBalancerAgent_UpdateServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).UpdateServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/UpdateServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).UpdateServers(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeLoadBalancerAgent_DeleteServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).DeleteServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/DeleteServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).DeleteServers(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeLoadBalancerAgent_GetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).GetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/GetAgentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).GetAgentStatus(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _NativeLoadBalancerAgent_GetServerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NativeLoadBalancerAgentServer).GetServerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.NativeLoadBalancerAgent/GetServerStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NativeLoadBalancerAgentServer).GetServerStats(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _NativeLoadBalancerAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.NativeLoadBalancerAgent",
	HandlerType: (*NativeLoadBalancerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServers",
			Handler:    _NativeLoadBalancerAgent_CreateServers_Handler,
		},
		{
			MethodName: "UpdateServers",
			Handler:    _NativeLoadBalancerAgent_UpdateServers_Handler,
		},
		{
			MethodName: "DeleteServers",
			Handler:    _NativeLoadBalancerAgent_DeleteServers_Handler,
		},
		{
			MethodName: "GetAgentStatus",
			Handler:    _NativeLoadBalancerAgent_GetAgentStatus_Handler,
		},
		{
			MethodName: "GetServerStats",
			Handler:    _NativeLoadBalancerAgent_GetServerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/native-lb.proto",
}
